---
- name: Sketchybar install
  when: ansible_os_family == "Darwin"
  block:
    - name: Add tap for sketchybar
      community.general.homebrew_tap:
        name: FelixKratz/formulae

    - name: Install sketchybar
      community.general.homebrew:
        name: felixkratz/formulae/sketchybar
        state: installed
        update_homebrew: true
