---
- name: install Spotify in Debian/Ubuntu
  become: true
  block:
    - name: add Spotify repo key
      ansible.builtin.apt_key:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        state: present

    - name: add Spotify repo
      ansible.builtin.apt_repository:
        filename: spotify
        repo: deb http://repository.spotify.com stable non-free
        state: present
    
    - name: install Spotify
      ansible.builtin.apt:
        name: spotify-client
        update_cache: yes
        state: latest
  when: ansible_os_family == "Debian" and 'WSL_DISTRO_NAME' not in ansible_env.keys()
