---
- name: download tmuxer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tjhop/tmuxer/master/tmuxer
    dest: "{{ ansible_facts.env.HOME }}/.local/bin/tmuxer"
    mode: '0755'
