---
  - name: install cheat
    command: go get -u github.com/cheat/cheat/cmd/cheat
    args:
      creates: "{{ ansible_facts.env.HOME }}/go/bin/cheat"
  
  - name: Create dir for cheat sheets
    file:
      path: "{{ ansible_facts.env.HOME }}/.config/cheat/cheetsheets/community"
      state: directory
      mode: 0755
  
  - name: download community cheat sheets
    git:
      repo: git@github.com:cheat/cheatsheets.git
      dest: "{{ ansible_facts.env.HOME }}/.config/cheat/cheetsheets/community"
  
  - name: setup custom Cheat configs
    file:
      src: "{{ playbook_dir }}/roles/cheat/files/{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop:
      - { src: "cheatconf.yml", dest: "{{ ansible_facts.env.HOME }}/.config/cheat/conf.yml"}
 