---
  - name: install cheat
    command: /usr/local/go/bin/go install github.com/cheat/cheat/cmd/cheat@latest
    args:
      creates: "{{ ansible_facts.env.HOME }}/go/bin/cheat"
  
  - name: Create dirs for cheat sheets
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    loop:
      - "{{ ansible_facts.env.HOME }}/.config/cheat/cheatsheets/community"
      - "{{ ansible_facts.env.HOME }}/.config/cheat/cheatsheets/personal"
  
  - name: download community cheat sheets
    git:
      repo: https://github.com/cheat/cheatsheets.git
      dest: "{{ ansible_facts.env.HOME }}/.config/cheat/cheatsheets/community"
  
  - name: download personal cheat sheets
    git:
      repo: https://github.com/wbh1/cheatsheets.git
      dest: "{{ ansible_facts.env.HOME }}/.config/cheat/cheatsheets/personal"
  
  - name: setup custom Cheat configs
    file:
      src: "{{ playbook_dir }}/roles/cheat/files/{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop:
      - { src: "cheatconf.yml", dest: "{{ ansible_facts.env.HOME }}/.config/cheat/conf.yml"}
 
