---
- hosts: localhost
  connection: local
  vars:
    GO_VERSION: 1.18.4
  roles:
    - name: zsh
      tags: zsh

    - name: dotfiles
      tags: dotfiles

    - name: programming
      tags: programming

    - name: k8s
      tags: k8s

    - name: cheat
      tags: cheat

    - name: espanso
      tags: espanso
      when: ansible_os_family == "Darwin"

    # Install assorted packages
    - name: pkgs
      tags: pkgs
    
    - name: apps
      tags: apps

    - name: fonts
      tags: fonts
      when: ansible_system == "Linux"

    - name: gnome
      tags: gnome
      when: ansible_env["GNOME_SHELL_SESSION_MODE"] is defined
