---
- hosts: localhost
  connection: local
  vars:
    GO_VERSION: 1.19.4
  roles:
    - name: zsh
      tags: zsh

    - name: dotfiles
      tags: dotfiles

    - name: programming
      tags: programming

    - name: k8s
      tags: k8s

    - name: cheat
      tags: cheat

    - name: espanso
      tags: espanso
      when: ansible_os_family == "Darwin"

    # Install assorted packages
    - name: pkgs
      tags: pkgs
    
    - name: repos
      tags: repos
    
    - name: apps
      tags: apps

    - name: fonts
      tags: fonts
      when: ansible_system == "Linux"
    
    - name: geerlingguy.docker
      become: true
      tags: docker
      when: ansible_system == "Linux"

    - name: desktop
      tags: desktop
      when: ansible_system == "Linux"
