---
  - hosts: localhost
    connection: local
    vars:
      GO_VERSION: 1.17.6
      k8s_version: v1.18.0
    roles:
      - { name: dotfiles, tags: dotfiles }
      - zsh
      - go
      - k8s
      - cheat
      - { name: espanso, tags: espanso }