---
  - hosts: localhost
    connection: local
    vars:
      GO_VERSION: 1.17.6
    roles:
      - { name: dotfiles, tags: dotfiles }
      - zsh
      - go
      - { name: k8s, tags: k8s }
      - cheat
      - { name: espanso, tags: espanso }
