---
  - hosts: localhost
    connection: local
    vars:
      GO_VERSION: 1.14.2
    roles:
      - zsh
      - dotfiles
      - go
    tasks:
      - name: install kubectl
        get_url:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
          dest: /usr/local/bin/kubectl
          mode: 0755

      - name: install kubectx/kubens
        become: yes
        block:
          - name: Download kubectx/kubens files
            git:
              repo: https://github.com/ahmetb/kubectx.git
              dest: /opt/kubectx
          - name: Link kubectx/kubens files
            file:
              src: "/opt/kubectx/{{ item }}"
              dest: "/usr/local/bin/{{ item }}"
              state: link
            loop:
              - kubectx
              - kubens