---
- name: install pop-os shell in Fedora
  become: true
  ansible.builtin.yum:
    name:
      - gnome-shell-extension-pop-shell
      - xprop
    state: latest
  when: ansible_distribution == "Fedora"
  notify: enable pop-shell

- name: install pop-shell shell in Ubuntu
  block:
    - name: install pop-shell deps
      become: true
      ansible.builtin.apt:
        name:
          - node-typescript
          - make
        state: present

    - name: create pop-shell repo directory
      ansible.builtin.file:
        path: "{{ ansible_env['HOME'] }}/github/pop-os/shell"
        state: directory

    - name: clone pop-shell repo
      ansible.builtin.git:
        depth: 1
        version: master
        repo: https://github.com/pop-os/shell.git
        dest: "{{ ansible_env['HOME'] }}/github/pop-os/shell"
      notify: build pop-shell
  when: ansible_distribution == "Ubuntu"

- name: install gnome-tweaks
  become: true
  ansible.builtin.package:
    name: gnome-tweaks
    state: present
  when: ansible_system == "Linux"

- name: install nord theme
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/EliverLara/Nordic/releases/latest/download/Nordic.tar.xz
    dest: /usr/share/themes
  notify: set nord theme
