---
- name: Verify creation of directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/profile.d
    - "{{ ansible_facts.env.HOME }}/.config/cheat"

- name: Template files that need templating
  become: yes
  template:
    src: "{{ item }}"
    dest: /etc/profile.d/{{ item | basename | splitext | first}}
  with_fileglob:
    - templates/*.j2
  loop_control:
    label: /etc/profile.d/{{ item | basename | splitext | first}}

- name: Create symlinks for dotfiles
  file:
    src: "{{ playbook_dir }}/roles/dotfiles/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: ".zshrc", dest: "{{ ansible_facts.env.HOME }}/.zshrc" }
    - { src: ".spacecowboy.sh", dest: "{{ ansible_facts.env.HOME }}/.spacecowboy.sh" }
    - { src: ".zlogout", dest: "{{ ansible_facts.env.HOME }}/.zlogout" }
    - { src: ".p10k.zsh", dest: "{{ ansible_facts.env.HOME }}/.p10k.zsh" }
    - { src: ".gitconfig", dest: "{{ ansible_facts.env.HOME }}/.gitconfig" }
    - { src: ".aliases", dest: "{{ ansible_facts.env.HOME }}/.aliases" }
    - { src: ".dircolors", dest: "{{ ansible_facts.env.HOME }}/.dircolors" }
    - { src: ".flake8", dest: "{{ ansible_facts.env.HOME }}/.flake8" }
    - { src: ".tmux.conf", dest: "{{ ansible_facts.env.HOME}}/.tmux.conf" }
    - { src: "cheatconf.yml", dest: "{{ ansible_facts.env.HOME }}/.config/cheat/conf.yml"}
