---
- name: Load variable file based on the OS type.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - 'default.yml'
      paths:
        - 'vars'

- name: ensure chezmoi is already installed by mise
  stat:
    path: "{{ ansible_facts.env.HOME }}/.local/share/mise/shims/chezmoi"
  register: chezmoi_shim

- name: Setup chezmoi for dotfiles
  block:
    - name: Initialize and apply chezmoi
      shell: chezmoi init --apply wbh1
      args:
        creates: ~/.local/share/chezmoi/
  when: chezmoi_shim.stat.exists
