---
  - name: install tools
    homebrew:
      name: "{{ item }}"
    when: ansible_os_family == "Darwin"
    loop:
      - kubernetes-cli  # kubectl
      - kubectx
      - fluxcd/tap/flux
      - helm
      - kustomize
