[tools]
usage = "latest"
teleport-community = "14.0.3"
rye = "0.36.0"
pint = "0.61.2"
bun = "latest"
goreleaser = "latest"
just = "latest"
node = "20"
yarn = "1"
pnpm = "latest"
"go:github.com/oz/tz" = "latest"
uv = "latest"
jq = "1.6"
bat = "0.24.0"
vault = "1.13.2+ent"
terraform = "1.3.6"
flux2 = "0.38.3"
pre-commit = "3.4.0"
yq = "4.35.2"
vale = "3.0.5"
kustomize = "5.3.0"
kubectl = "1.29.1"
kubectx = "0.9.5"
age = "1.1.1"
sops = "3.8.1"
k9s = "0.32.5"
ripgrep = "14.1.0"

[settings]
experimental = true
