---
- name: ZSH Installation
  block:
    - name: Install ZSH via Linux package manager
      become: yes
      package:
        name: zsh
        state: present
      when: ansible_facts["system"] == "Linux"
  rescue:
    - name: Try again in case of python3-apt error
      become: yes
      ansible.builtin.package:
        name: zsh
        state: present

- name: Set ZSH as default shell
  become: true
  user:
    shell: /usr/bin/zsh
    name: "{{ ansible_facts.user_id }}"
  when: ansible_facts["system"] == "Linux"

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: install ZSH plugins
  git:
    repo: https://github.com/{{ item.org }}/{{ item.name }}.git
    dest: "{{ ansible_facts.env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  when: ansible_facts.env.ZSH is defined and ".oh-my-zsh" in ansible_facts.env.ZSH
  loop:
    - org: unixorn
      name: fzf-zsh-plugin
    - org: zsh-users
      name: zsh-syntax-highlighting
    - org: zsh-users
      name: zsh-autosuggestions
    - org: Aloxaf
      name: fzf-tab
