---
# Defaults are presumed to be for Linux (Debian or RedHat based)
dotfiles:
  dirs:
    - /etc/profile.d
    - "{{ ansible_facts.env.HOME }}/.config/cheat"
    - "{{ ansible_facts.env.HOME }}/.config/sway"
    - "{{ ansible_facts.env.HOME }}/.config/waybar"
    - "{{ ansible_facts.env.HOME }}/.config/alacritty"
    - "{{ ansible_facts.env.HOME }}/.config/rofi/themes"
  files:
    - { src: ".zshrc", dest: "{{ ansible_facts.env.HOME }}/.zshrc" }
    - { src: ".spacecowboy.sh", dest: "{{ ansible_facts.env.HOME }}/.spacecowboy.sh" }
    - { src: ".zlogout", dest: "{{ ansible_facts.env.HOME }}/.zlogout" }
    - { src: ".p10k.zsh", dest: "{{ ansible_facts.env.HOME }}/.p10k.zsh" }
    - { src: ".gitconfig", dest: "{{ ansible_facts.env.HOME }}/.gitconfig" }
    - { src: ".aliases", dest: "{{ ansible_facts.env.HOME }}/.aliases" }
    - { src: ".dircolors", dest: "{{ ansible_facts.env.HOME }}/.dircolors" }
    - { src: ".flake8", dest: "{{ ansible_facts.env.HOME }}/.flake8" }
    - { src: ".tmux.conf", dest: "{{ ansible_facts.env.HOME }}/.tmux.conf" }
    - { src: "alacritty.yml", dest: "{{ ansible_facts.env.HOME }}/.config/alacritty/alacritty.yml" }
    - { src: "sway", dest: "{{ ansible_facts.env.HOME }}/.config/sway/config" }
    - { src: "waybar/config", dest: "{{ ansible_facts.env.HOME }}/.config/waybar/config" }
    - { src: "waybar/style.css", dest: "{{ ansible_facts.env.HOME }}/.config/waybar/style.css" }
