---
- name: install Go
  ansible.builtin.include_tasks:
    file: go.yml
    apply:
      tags: ["go"]

- name: install Rust
  ansible.builtin.include_tasks:
    file: rust.yml
    apply:
      tags: ["rust"]
