---
pkgs:
  - direnv
  - NetworkManager
  - dunst
  - light
  - sway
  - waybar
  - rofi-wayland
  - polkit-gnome
  - mousepad
  - pavucontrol
  - pulseaudio-utils
  - docker-compose-plugin
  - copyq
