pkgs:
  - gnu-sed
  - curl
  - bash
  - gpg
  # Below are for Ruby
  # https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
  # https://mise.jdx.dev/lang/ruby.html#usage
  - openssl@3
  - readline
  - libyaml
  - gmp
  - autoconf
