---
pkgs:
  - direnv
  - tmux
  - rofi
  - syncthing
  - copyq
  - ripgrep
  - jq
  - pulseeffects
  - xclip
  - graphviz

services:
  user:
    - name: syncthing
      state: started
      enabled: true
