---
- name: reload font-cache
  become: true
  shell: fc-cache -v
  listen: "reload font-cache"

- name: set gnome fonts
  ansible.builtin.command: gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font 10'
