---
  - name: Download Go (Linux)
    become: yes
    unarchive:
      src: https://dl.google.com/go/go{{GO_VERSION}}.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes
      creates: /usr/local/go
    when: ansible_system == "Linux"

  - name: Download Go (Mac)
    homebrew:
      name: go
      state: latest
    when: ansible_system == "Darwin"