---

- name: install vscode
  ansible.builtin.include_tasks: vscode.yml

- name: install 1password
  ansible.builtin.include_tasks: 1password.yml

- name: install obsidian
  ansible.builtin.include_tasks: obsidian.yml

- name: install alfred
  ansible.builtin.include_tasks: alfred.yml
  when: ansible_os_family == "Darwin"
