---
- name: read vars from first file found, use 'vars/' relative subdir
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: install {{ item }} 
  ansible.builtin.include_tasks:
    file: "{{ item }}.yml"
  loop:
    - vscode
    - 1password
    - obsidian
    # Slack install disabled since I manually installed a .deb
    # - slack
    - tmuxer
    - spotify
    - todoist
    - alacritty

- name: install alfred
  ansible.builtin.include_tasks: alfred.yml
  when: ansible_os_family == "Darwin"
