---
- name: read vars from first file found, use 'vars/' relative subdir
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: install {{ item }} 
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_fileglob:
    - "tasks/apps/*.yml"
