---
- name: read vars from first file found, use 'vars/' relative subdir
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: install {{ item }}
  ansible.builtin.include_tasks:
    file: "tasks/apps/{{ item }}.yml"
  loop: "{{ lookup('fileglob', 'tasks/apps/*.yml', wantlist=True)|map('regex_replace', '\\.yml', '')|map('basename')|reject('in', apps['disabled']) }}"

