- name: Load variable file based on the OS type.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - 'default.yml'
      paths:
        - 'vars'

- name: Install Mac packages
  homebrew:
    name: "{{ pkgs }}"
    state: present
  when: pkgs is defined and pkgs|length > 0 and ansible_os_family == "Darwin"

- name: Install Linux packages
  become: yes
  package:
    name: "{{ pkgs }}"
    state: latest
  when: pkgs is defined and pkgs|length > 0 and ansible_system == "Linux"
