- name: Load variable file based on the OS type.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - 'default.yml'
      paths:
        - 'vars'

- name: Configure additional Ubuntu repos
  block:
    - name: Add Ubuntu apt key
      ansible.builtin.apt_key:
        keyserver: "{{ item.key.server }}"
        id: "{{ item.key.id }}"
        state: present
      when: item.key is defined and item.key
      loop: "{{ pkg_repos }}"

    - name: Add Ubuntu apt repo
      ansible.builtin.apt_repository:
        repo: "{{ item.link }}"
        state: present 
      when: item.link is defined and item.link
      loop: "{{ pkg_repos }}"
  when: >
    ansible_distribution == "Ubuntu"
    and pkg_repos is defined
    and pkg_repos

- name: Install Mac packages
  homebrew:
    name: "{{ pkgs }}"
    state: present
  when: pkgs is defined and pkgs|length > 0 and ansible_os_family == "Darwin"

- name: Install Linux packages
  become: yes
  package:
    name: "{{ pkgs }}"
    state: latest
  when: pkgs is defined and pkgs|length > 0 and ansible_system == "Linux"

- name: Configure systemd user services
  systemd:
    name: "{{ item.name }}"
    scope: user
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(True) }}"
  loop: "{{ services.user }}"
  when: services is defined and services.user is defined and ansible_system == "Linux"
