- name: Load variable file based on the OS type.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
      paths:
        - 'vars'

- name: Install Mac packages
  homebrew:
    name: "{{ pkgs }}"
    state: present
  when: ansible_os_family == "Darwin"
