---
- name: Create NerdFonts directories
  file:
    path: "{{ ansible_env['HOME'] }}/.local/share/fonts/NerdFonts/{{ item }}"
    state: directory
  loop: "{{ fonts }}"

- name: Install {{ item }}
  unarchive:
    remote_src: true
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip"
    dest: "{{ ansible_env['HOME'] }}/.local/share/fonts/NerdFonts/{{ item }}"
    creates: "{{ ansible_env['HOME'] }}/.local/share/fonts/NerdFonts/{{ item }}/.installed"
  loop: "{{ fonts }}"

- name: Mark {{ item }} as installed
  file:
    path: "{{ ansible_env['HOME'] }}/.local/share/fonts/NerdFonts/{{ item }}/.installed"
    state: touch
    access_time: preserve
    modification_time: preserve
  loop: "{{ fonts }}"
